version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: kgdb

  adminer:
    image: adminer
    restart: 'always'
    links:
      - mysql
    ports:
      - 8080:8080

  composer:
    restart: 'no'
    image: composer
    command: update
    volumes:
    - .:/app