version: '3'

services:

  webserver:
    build: ./httpd
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - .:/var/www/html/
      - ./httpd:/etc/apache2/sites-available
    ports:
      - 8080:80
    working_dir: /var/www/html/

  mysqlserver:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: kgdb
    volumes:
      - ./databases:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  composer:
    image: composer:latest
    volumes:
      - .:/var/www/html/
    working_dir: /var/www/html/
    command: composer install