<?php

namespace app\controllers;

use Yii;
use yii\filters\VerbFilter;
use yii\rest\ActiveController;

/**
 * EmployeeController implements the CRUD actions for Employee model.
 */
class AccountController extends ActiveController
{

    public $modelClass = 'app\models\Account';

    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors['verbs']['class'] = VerbFilter::class;
        $behaviors['contentNegotiator'] = [
            'class' => \yii\filters\ContentNegotiator::class,
            'formats' => [
                'application/json' => \yii\web\Response::FORMAT_JSON,
            ],
        ];

        return $behaviors;
    }

    public function actions()
    {
        return [
            'accrue' => [
                'class' => 'app\controllers\accountActions\AccrueAction',
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
            ],
            'lock' => [
                'class' => 'app\controllers\accountActions\LockAction',
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
            ],
            'view' => [
                'class' => 'app\controllers\accountActions\ViewAction',
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
            ],
            'create' => [
                'class' => 'app\controllers\accountActions\CreateAction',
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
            ],
            'transfer' => [
                'class' => 'app\controllers\accountActions\TransferAction',
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
            ],
        ];
    }

    public function checkAccess($action, $model = null, $params = [])
    {
        parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }
}